2024/11/20 12:23:48 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "localhost", referrer: "http://localhost/"
2024/11/20 12:23:48 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "localhost", referrer: "http://localhost/"
2024/11/20 12:23:49 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "localhost", referrer: "http://localhost/"
2024/11/20 12:23:49 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "localhost", referrer: "http://localhost/"
